# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef943ff093e7cd2ca9f99f67214cc7852fff0ed7f98c81845e7922c8e9c744a34a33fcf6a57f38417487b85df6192b9486304b330242434a404235b8826092a

test:
  secret_key_base: b7a7ef8040f0382ec757b6ec9c958d4dcb27acc5e3e08e01932496709b251d3dc3671df2a8d27c3bd5e4c31a7fca043822815c90631b694258c59396431a8d4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
